name: test workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "first step executed"

      - name: second step
        run: echo "second step executed"

  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies (frontend)
        working-directory: frontend
        run: npm install

      - name: run dev (frontend)
        working-directory: frontend
        run: npm run dev
