name: test workflow

on:
  push:
  workflow_dispatch:

# This is required to allow the action to push changes back to main
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "first step executed"

      - name: second step
        run: echo "second step executed"
      - name: fail if TODO exists
        run: |
          if grep -R "TODO" .; then
            echo "Found TODO. Failing build."
            exit 1
          else
            echo "No TODOs found."
        
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fetch the repo
        run: |
          ls -a
          echo "repo downloaded"
      - name: second step of second job
        run: echo "end"
